// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcTXM2ARW8U-5o5uspbR5G0v0kT5JdF58',
    appId: '1:114554009961:web:1a42b4854c434303c0a5f8',
    messagingSenderId: '114554009961',
    projectId: 'rasi-electricals',
    authDomain: 'rasi-electricals.firebaseapp.com',
    databaseURL: 'https://rasi-electricals-default-rtdb.firebaseio.com',
    storageBucket: 'rasi-electricals.firebasestorage.app',
    measurementId: 'G-6C9K8PKM66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl_VA_spck5PJy7yChcNrg8vGjGRz_kxk',
    appId: '1:114554009961:android:3cc7daffd92e35c1c0a5f8',
    messagingSenderId: '114554009961',
    projectId: 'rasi-electricals',
    databaseURL: 'https://rasi-electricals-default-rtdb.firebaseio.com',
    storageBucket: 'rasi-electricals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHFTjV16gI68P3h_jwmKNnfgGLrC7RYBw',
    appId: '1:114554009961:ios:0f7a6de3da5d4119c0a5f8',
    messagingSenderId: '114554009961',
    projectId: 'rasi-electricals',
    databaseURL: 'https://rasi-electricals-default-rtdb.firebaseio.com',
    storageBucket: 'rasi-electricals.firebasestorage.app',
    iosClientId: '114554009961-ocrsugm5m011klgcf57pgrmgf3iro1s7.apps.googleusercontent.com',
    iosBundleId: 'com.rasielectricals.customer',
  );
}
